module.exports = [
  {
    type: "function",
    name: "advertiserIsBlamed",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [
      { name: "isBlamed", type: "bool", internalType: "bool" },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
      { name: "votesFor", type: "uint256", internalType: "uint256" },
      { name: "votesAgainst", type: "uint256", internalType: "uint256" },
      { name: "resolved", type: "bool", internalType: "bool" },
      {
        name: "blameSecurityDeposit",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "blameSecurityDepositReturned",
        type: "bool",
        internalType: "bool",
      },
      { name: "proposer", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "blameAdvertiser",
    inputs: [
      { name: "advertiser", type: "address", internalType: "address" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "v", type: "uint8", internalType: "uint8" },
      { name: "r", type: "bytes32", internalType: "bytes32" },
      { name: "s", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "blameAdvertiserApprove",
    inputs: [{ name: "advertiser", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createProposal",
    inputs: [
      { name: "_duration", type: "uint256", internalType: "uint256" },
      { name: "_pricePerBillboard", type: "uint256", internalType: "uint256" },
      { name: "_securityDeposit", type: "uint256", internalType: "uint256" },
      { name: "_minVotingTokens", type: "uint256", internalType: "uint256" },
      {
        name: "_securityDepositAdvertiser",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "v", type: "uint8", internalType: "uint8" },
      { name: "r", type: "bytes32", internalType: "bytes32" },
      { name: "s", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createProposalApprove",
    inputs: [
      { name: "_duration", type: "uint256", internalType: "uint256" },
      { name: "_pricePerBillboard", type: "uint256", internalType: "uint256" },
      { name: "_securityDeposit", type: "uint256", internalType: "uint256" },
      { name: "_minVotingTokens", type: "uint256", internalType: "uint256" },
      {
        name: "_securityDepositAdvertiser",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "duration",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "executeProposal",
    inputs: [{ name: "proposalId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAdvertiserIsBlamed",
    inputs: [{ name: "advertiser", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct BillboardGovernance.AdvertiserIsBlamed",
        components: [
          { name: "isBlamed", type: "bool", internalType: "bool" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "votesFor", type: "uint256", internalType: "uint256" },
          { name: "votesAgainst", type: "uint256", internalType: "uint256" },
          { name: "resolved", type: "bool", internalType: "bool" },
          {
            name: "blameSecurityDeposit",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "blameSecurityDepositReturned",
            type: "bool",
            internalType: "bool",
          },
          { name: "proposer", type: "address", internalType: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProposal",
    inputs: [{ name: "proposalId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "_duration", type: "uint256", internalType: "uint256" },
      { name: "_pricePerBillboard", type: "uint256", internalType: "uint256" },
      { name: "_securityDeposit", type: "uint256", internalType: "uint256" },
      {
        name: "_initialSecurityDeposit",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "_minVotingTokens", type: "uint256", internalType: "uint256" },
      { name: "_votesFor", type: "uint256", internalType: "uint256" },
      { name: "_votesAgainst", type: "uint256", internalType: "uint256" },
      { name: "_executed", type: "bool", internalType: "bool" },
      { name: "_createdAt", type: "uint256", internalType: "uint256" },
      {
        name: "_securityDepositAdvertiser",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasVoted",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasVotedForBlame",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_duration", type: "uint256", internalType: "uint256" },
      { name: "_pricePerBillboard", type: "uint256", internalType: "uint256" },
      { name: "_securityDeposit", type: "uint256", internalType: "uint256" },
      { name: "_token", type: "address", internalType: "address" },
      {
        name: "_securityDepositAdvertiser",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "_minVotingTokens", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "minVotingTokens",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pricePerBillboard",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proposalCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proposals",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "duration", type: "uint256", internalType: "uint256" },
      { name: "pricePerBillboard", type: "uint256", internalType: "uint256" },
      { name: "securityDeposit", type: "uint256", internalType: "uint256" },
      {
        name: "initialSecurityDeposit",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "minVotingTokens", type: "uint256", internalType: "uint256" },
      { name: "votesFor", type: "uint256", internalType: "uint256" },
      { name: "votesAgainst", type: "uint256", internalType: "uint256" },
      { name: "executed", type: "bool", internalType: "bool" },
      { name: "proposer", type: "address", internalType: "address" },
      { name: "depositReturned", type: "bool", internalType: "bool" },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
      {
        name: "securityDepositAdvertiser",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolveAdvertiserBlame",
    inputs: [{ name: "advertiser", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "returnSecurityDeposit",
    inputs: [{ name: "proposalId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "returnSecurityDepositForBlame",
    inputs: [{ name: "advertiser", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "securityDeposit",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "securityDepositAdvertiser",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "token",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract BillboardToken" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateSecurityDepositAdvertiser",
    inputs: [
      {
        name: "_securityDepositAdvertiser",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "vote",
    inputs: [
      { name: "proposalId", type: "uint256", internalType: "uint256" },
      { name: "support", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "voteForBlame",
    inputs: [
      { name: "advertiser", type: "address", internalType: "address" },
      { name: "support", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AdvertiserBlameResolved",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "resolved", type: "bool", indexed: true, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AdvertiserBlamed",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      {
        name: "advertiser",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      {
        name: "version",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProposalCreated",
    inputs: [
      {
        name: "proposalId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "duration",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "pricePerBillboard",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "securityDeposit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "minVotingTokens",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "createdAt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "securityDepositAdvertiser",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProposalExecuted",
    inputs: [
      {
        name: "proposalId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SecurityDepositReturned",
    inputs: [
      {
        name: "proposalId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "proposer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SecurityDepositReturnedForBlame",
    inputs: [
      {
        name: "advertiser",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "proposer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Voted",
    inputs: [
      {
        name: "proposalId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "voter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "support", type: "bool", indexed: false, internalType: "bool" },
      {
        name: "votes",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VotedForBlame",
    inputs: [
      {
        name: "voter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "advertiser",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "support", type: "bool", indexed: false, internalType: "bool" },
      {
        name: "votes",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
];
