module.exports = [
  { inputs: [], type: 'error', name: 'InvalidInitialization' },
  { inputs: [], type: 'error', name: 'NotInitializing' },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    type: 'error',
    name: 'OwnableInvalidOwner',
  },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
  },
  {
    inputs: [
      { internalType: 'address', name: 'owner', type: 'address', indexed: true },
      { internalType: 'uint256', name: 'index', type: 'uint256', indexed: false },
      { internalType: 'uint256', name: 'newExpiryTime', type: 'uint256', indexed: false },
    ],
    type: 'event',
    name: 'BillboardExtended',
    anonymous: false,
  },
  {
    inputs: [
      { internalType: 'address', name: 'buyer', type: 'address', indexed: true },
      { internalType: 'uint256', name: 'expiryTime', type: 'uint256', indexed: false },
      { internalType: 'string', name: 'description', type: 'string', indexed: false },
      { internalType: 'string', name: 'link', type: 'string', indexed: false },
      { internalType: 'string', name: 'ipfsHash', type: 'string', indexed: false },
    ],
    type: 'event',
    name: 'BillboardPurchased',
    anonymous: false,
  },
  {
    inputs: [{ internalType: 'uint64', name: 'version', type: 'uint64', indexed: false }],
    type: 'event',
    name: 'Initialized',
    anonymous: false,
  },
  {
    inputs: [
      { internalType: 'address', name: 'previousOwner', type: 'address', indexed: true },
      { internalType: 'address', name: 'newOwner', type: 'address', indexed: true },
    ],
    type: 'event',
    name: 'OwnershipTransferred',
    anonymous: false,
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    name: 'billboards',
    outputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'uint256', name: 'expiryTime', type: 'uint256' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'string', name: 'link', type: 'string' },
      { internalType: 'string', name: 'ipfsHash', type: 'string' },
    ],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'duration',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'extendBillboard',
  },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
    name: 'getBillboards',
    outputs: [
      {
        internalType: 'struct BillboardRegistry.Billboard[]',
        name: '',
        type: 'tuple[]',
        components: [
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'uint256', name: 'expiryTime', type: 'uint256' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'string', name: 'link', type: 'string' },
          { internalType: 'string', name: 'ipfsHash', type: 'string' },
        ],
      },
    ],
  },
  {
    inputs: [{ internalType: 'address', name: '_usdcAddress', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'initialize',
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'pricePerBillboard',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    inputs: [
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'string', name: 'link', type: 'string' },
      { internalType: 'string', name: 'ipfsHash', type: 'string' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'purchaseBillboard',
  },
  { inputs: [], stateMutability: 'nonpayable', type: 'function', name: 'renounceOwnership' },
  {
    inputs: [{ internalType: 'uint256', name: 'newDuration', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setDuration',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'newPrice', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setPricePerBillboard',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'transferOwnership',
  },
  {
    inputs: [],
    stateMutability: 'view',
    type: 'function',
    name: 'usdc',
    outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
  },
  { inputs: [], stateMutability: 'nonpayable', type: 'function', name: 'withdrawFunds' },
];
