name: Build and Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install npm first (should come with Node)
      - name: Verify npm installation
        run: |
          node --version
          npm --version

      # Install and setup Yarn
      - name: Setup Yarn
        run: |
          npm install -g corepack
          corepack enable
          corepack prepare yarn@4.6.0 --activate
          yarn set version 4.6.0

      # Verify Yarn installation
      - name: Verify Yarn installation
        run: |
          yarn --version
          which yarn

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: |
          yarn install --immutable
          yarn cache clean

      - name: Build packages
        run: |
          yarn build

      - name: Run tests
        run: yarn test

  cypress-run:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install UI dependencies
        run: yarn install

      - name: Start UI server
        run: yarn start &

      - name: Wait for UI to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: yarn cypress run --headless
