name: Build and Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Verify npm installation
        run: |
          node --version
          npm --version

      - name: Setup Yarn
        run: |
          npm install -g corepack
          corepack enable
          corepack prepare yarn@4.6.0 --activate
          yarn set version 4.6.0

      - name: Verify Yarn installation
        run: |
          yarn --version
          which yarn

      - name: Install dependencies
        run: |
          yarn install --immutable
          yarn cache clean

      - name: Build packages
        run: |
          yarn build

      - name: Run tests
        run: yarn test

      - name: Run UI server and Cypress tests
        run: |
          cd ./packages/ui && yarn dev & UI_PID=$!
          cd ../cypress && yarn cypress run --headless
          kill $UI_PID
