name: Build and Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Verify npm installation
        run: |
          node --version
          npm --version

      - name: Setup Yarn
        run: |
          npm install -g corepack
          corepack enable
          corepack prepare yarn@4.6.0 --activate
          yarn set version 4.6.0

      - name: Verify Yarn installation
        run: |
          yarn --version
          which yarn

      - name: Install dependencies
        run: |
          yarn install --immutable
          yarn cache clean

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd packages/contracts && forge test -vvv
        id: test

      - name: Build packages
        run: |
          yarn build

      - name: Run tests
        run: yarn test

      - name: Run UI server and Cypress tests
        run: |
          cd ./packages/ui && yarn dev & UI_PID=$!
          cd ./packages/cypress && yarn cypress run --headless
          cd ./packages/cypress && yarn test:component --headless
          kill $UI_PID
