name: Cypress Tests

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./billboard/packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install root dependencies
        run: npm install
        working-directory: ./billboard/packages/ui

      - name: Install Cypress dependencies
        run: npm install
        working-directory: ./billboard/packages/cypress

      - name: Start UI server
        run: npm start &
        working-directory: ./billboard/packages/ui

      - name: Wait for UI to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: npx cypress run --headless
        working-directory: ./billboard/packages/cypress
